//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types;
using CMS.CustomTables;

[assembly: RegisterCustomTable(PaymentechProfileItem.CLASS_NAME, typeof(PaymentechProfileItem))]

namespace CMS.CustomTables.Types
{
    /// <summary>
    /// Sample item class.
    /// </summary>
    public partial class PaymentechProfileItem : CustomTableItem
    {
        #region "Constants"

        /// <summary>
        /// Class name of the item.
        /// </summary>
        public const string CLASS_NAME = "RG.PaymentechProfile";

        #endregion


        #region "Properties"

        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public bool IsActive
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("IsActive"), false);
            }
            set
            {
                SetValue("IsActive", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public long MerchantID
        {
            get
            {
                return ValidationHelper.GetLong(GetValue("MerchantID"), 0);
            }
            set
            {
                SetValue("MerchantID", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public bool IsRecurring
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("IsRecurring"), false);
            }
            set
            {
                SetValue("IsRecurring", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string MaskedAccountNumber
        {
            get
            {
                return ValidationHelper.GetString(GetValue("MaskedAccountNumber"), "");
            }
            set
            {
                SetValue("MaskedAccountNumber", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string Expiration
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Expiration"), "");
            }
            set
            {
                SetValue("Expiration", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string CardBrand
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CardBrand"), "");
            }
            set
            {
                SetValue("CardBrand", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public DateTime LastTransactionUtc
        {
            get
            {
                return ValidationHelper.GetDateTime(GetValue("LastTransactionUtc"), DateTimeHelper.ZERO_TIME);
            }
            set
            {
                SetValue("LastTransactionUtc", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string CardholderName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CardholderName"), "");
            }
            set
            {
                SetValue("CardholderName", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public int CustomerID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("CustomerID"), 0);
            }
            set
            {
                SetValue("CustomerID", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public long CustomerRefNum
        {
            get
            {
                return ValidationHelper.GetLong(GetValue("CustomerRefNum"), 0);
            }
            set
            {
                SetValue("CustomerRefNum", value);
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor.
        /// </summary>
        public PaymentechProfileItem()
            : base(CLASS_NAME)
        {
        }

        #endregion
    }
}
