//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types;
using CMS.CustomTables;

[assembly: RegisterCustomTable(PaymentechTransactionItem.CLASS_NAME, typeof(PaymentechTransactionItem))]

namespace CMS.CustomTables.Types
{
    /// <summary>
    /// Sample item class.
    /// </summary>
    public partial class PaymentechTransactionItem : CustomTableItem
    {
        #region "Constants"

        /// <summary>
        /// Class name of the item.
        /// </summary>
        public const string CLASS_NAME = "RG.PaymentechTransaction";

        #endregion


        #region "Properties"

        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string TransactionRequest
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TransactionRequest"), "");
            }
            set
            {
                SetValue("TransactionRequest", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string TransactionResponse
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TransactionResponse"), "");
            }
            set
            {
                SetValue("TransactionResponse", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string GatewayOrderID
        {
            get
            {
                return ValidationHelper.GetString(GetValue("GatewayOrderID"), "");
            }
            set
            {
                SetValue("GatewayOrderID", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string HostResponseCode
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HostResponseCode"), "");
            }
            set
            {
                SetValue("HostResponseCode", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public int CustomerID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("CustomerID"), 0);
            }
            set
            {
                SetValue("CustomerID", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public int OrderID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("OrderID"), 0);
            }
            set
            {
                SetValue("OrderID", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public long PaymentProfileID
        {
            get
            {
                return ValidationHelper.GetLong(GetValue("PaymentProfileID"), 0);
            }
            set
            {
                SetValue("PaymentProfileID", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public long MerchantID
        {
            get
            {
                return ValidationHelper.GetLong(GetValue("MerchantID"), 0);
            }
            set
            {
                SetValue("MerchantID", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string TransactionType
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TransactionType"), "");
            }
            set
            {
                SetValue("TransactionType", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string TransactionReference
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TransactionReference"), "");
            }
            set
            {
                SetValue("TransactionReference", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string AuthorizationCode
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AuthorizationCode"), "");
            }
            set
            {
                SetValue("AuthorizationCode", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string ProcStatusMessage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ProcStatusMessage"), "");
            }
            set
            {
                SetValue("ProcStatusMessage", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public bool IsSuccess
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("IsSuccess"), false);
            }
            set
            {
                SetValue("IsSuccess", value);
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor.
        /// </summary>
        public PaymentechTransactionItem()
            : base(CLASS_NAME)
        {
        }

        #endregion
    }
}
